### ISSUE TITLE
Support extracted comments

### ISSUE THREAD

**Issue by mondeja** [mondeja/mdpo#107]
> `#. `

Blocked by #106

**Comment by SantosSi** [comment]
Dear @mondeja Please reopen this, because according to Weblate `#` is a comment FROM a translator, not FOR the translator and not supported as such by Weblate (https://github.com/WeblateOrg/weblate/issues/8260#issuecomment-1289355788). So, to make the comments appear in Weblate as hints to the translators and to stay in the POT files also after md2po updating them, it makes sense to make md2po keeping the `#.` comments.

**Comment by SantosSi** [comment]
The intention is to not touch the source md files to:
- ensure better human readability,
- avoid probably markdownlinter complaining about HTML content (untested)
- and leave them as much original as possible for alternative translation methods, like direct md to md translations.
Instead, the goal is to concentrate the translator activities and data in pot (and their po) files, here through comments in pot files.

**Comment by mondeja** [comment]
Use `--save` along with `--po-filepath` to avoid the stripping. Example:

Markdown:

```md
Some text that needs to be clarified
```

PO:

```po
#
msgid ""
msgstr ""

#. This is a comment for a translator
msgid "Some text that needs to be clarified"
msgstr ""
```

Execution: `md2po foo.md -s -p foo.po`

**Comment by SantosSi** [comment]
That's strange, because I already used the options (version 1.0.3):
md2po -q -w 0 -d 'Content-Type: text/plain; charset=UTF-8' -d 'Language: en' -s --pofilepath ../resources/pot_files/content/"$1".pot --po-encoding UTF-8 ../content/"$1".md
Can you spot the problem?

**Comment by SantosSi** [comment]
I might have found the problem: `--pofilepath` seems not to be fully equivalent to `-p`!
After I changed the option to -p in my command above, it preserves the `#.` comments.

**Comment by mondeja** [comment]
> Can you spot the problem?

No, please share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

> I might have found the problem: --pofilepath seems not to be fully equivalent to -p!

That's not possible, you've done something else.
