### ISSUE TITLE
Raise error if '--po-filepath' not found running md2po

### ISSUE THREAD

**Issue by dingyifei** [mondeja/mdpo#125]
When I tried to run the script on my computer locally, it works and produced correct results, but when I try to use Github Action to run and commit, it doesn't work. The po files and md files both got emptied. It seems like it doesn't have any permission to read these files, yet it is able to write them. Here is my repo where I tried to isolate things and test it. 

https://github.com/dingyifei/test-mdpo

**Comment by dingyifei** [comment]
![图片](https://user-images.githubusercontent.com/15083013/123605455-6f293980-d82e-11eb-814a-1cdd3d7a002f.png)
I'm not sure what's causing it. MDPO definitely ran but nothing was produced by it.

**Comment by mondeja** [comment]
Are you sure that the correct name of the file is `readme.md`? I only see a `README.md` in your repository :thinking:

**Comment by dingyifei** [comment]
Sorry for the confusion, I modified the yml and now it's README.md, but the issue still persists. 

![图片](https://user-images.githubusercontent.com/15083013/123607232-42762180-d830-11eb-9ddd-01991593a9e2.png)

Even with README.md, the result produced doesn't match the output in MinGW. You can see the cat command correctly read the file, but md2po doesn't read the file correctly. I suspect md2po is treating the path as a string or something?

![图片](https://user-images.githubusercontent.com/15083013/123606918-f75c0e80-d82f-11eb-9262-48939b4fc7a7.png)

**Comment by dingyifei** [comment]
I tried to put the directories in double-quotes, but it doesn't help either.

**Comment by mondeja** [comment]
Currently, if the PO file defined in `--po-filepath` argument doesn't exists, is not created, just [their content is printed to STDOUT](https://github.com/dingyifei/test-mdpo/runs/2930007322?check_suite_focus=true#step:5:1). This is by design, to enforce best practices creating PO files with metadata... but this could change if doesn't makes sense. I'm fine with whatever reasonable way, what was you expecting?

Aditionally, the argument `-e` was replaced by `--md-encoding` and `--po-encoding`.

**Comment by dingyifei** [comment]
The readme.po file is present in the repo https://github.com/dingyifei/test-mdpo/blob/main/readme.po It's just the output being commented (because the original has these strings uncommented as I produce them from my PC) Which means the output is different due to the platform difference.

` Currently, if the PO file defined in --po-filepath argument doesn't exists, is not created, just their content is printed to STDOUT. `
While this isn't the issue, I think automatically creating the PO file makes more sense

**Comment by mondeja** [comment]
I'm not sure why isn't recognized `readme.po` as a existing file. Maybe you shouldn't define the paths absolute, I'm not sure because I've never tried absolute paths in Github Actions. Could you remove the `-e` argument, use relative paths and try again? Additionally, you can check if Python can access to the file with `python -c "import os;print(os.path.exists('readme.po'));"`.

> I think automatically creating the PO file makes more sense

Why? I'm not sure. Should be created with metadata or not? Should the metadata include the encoding according to `--po-encoding`? A file without defined encoding will work in some languages like chinese? I just doesn't have the needed info to create a consistent PO file automatically for everybody.

**Comment by dingyifei** [comment]
> Why? I'm not sure. Should be created with metadata or not? Should the metadata include the encoding according to --po-encoding? A file without defined encoding will work in some languages like chinese? I just doesn't have the needed info to create a consistent PO file automatically for everybody.

Agree, since there are not enough information to create consistent data, raise an error might be a more consistent behavior since in the case of an automated script, user might not be aware of whether the PO file is created. 

They produced the same result regardless of the encoding and relative path. The test result of read permission is `true`. 
![图片](https://user-images.githubusercontent.com/15083013/123618379-b9b0b300-d83a-11eb-95fd-2fa0cd2ae137.png)

![图片](https://user-images.githubusercontent.com/15083013/123618096-75251780-d83a-11eb-842a-27e745c00fdb.png)

**Comment by dingyifei** [comment]
I'm not sure `raising error  '--po-filepath' not found running md2po` enhancement also addresses the different results when I'm running md2po in Github Action containers. 

For some reason, the strings extracted from README.md got commented out, whereas if I run it on my PC, it uncommented the commented strings. I'm not sure how it produces these strange results when the readme.po/readme2.po/readme3.po is present in the repo.

![图片](https://user-images.githubusercontent.com/15083013/123636692-bf64c380-d84f-11eb-9a64-eb1f0ea2315f.png)
![图片](https://user-images.githubusercontent.com/15083013/123636853-ed4a0800-d84f-11eb-8f8f-d33caf7af562.png)

**Comment by mondeja** [comment]
I'm not able to reproduce it, but anyways why are you using a file with obsolete messages file as input?

**Comment by dingyifei** [comment]
[update_locales.yml.txt](https://github.com/mondeja/mdpo/files/6788333/update_locales.yml.txt)

The above file is my Action workflow which reproduces the issue in the simplest form. It appears to me that the way md2po read file is different from the cat command, where pipe the cat output as STDIN for md2po produces the correct result.

![图片](https://user-images.githubusercontent.com/15083013/125015314-d9996f80-e0a1-11eb-8a6b-d43010fe16a3.png)

**Comment by dingyifei** [comment]
I tried to use `> filename md2po` for my script, but it seems like the `>` uses a codec other than utf-8 and result in the following error:
```
Traceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\md2po-script.py", line 33, in <module>
    sys.exit(load_entry_point('mdpo==0.3.19', 'console_scripts', 'md2po')())
  File "c:\program files\python39\lib\site-packages\mdpo\md2po\__main__.py", line 157, in main
    sys.exit(run(args=sys.argv[1:])[1])  # pragma: no cover
  File "c:\program files\python39\lib\site-packages\mdpo\md2po\__main__.py", line 148, in run
    pofile = markdown_to_pofile(opts.glob_or_content, **kwargs)
  File "c:\program files\python39\lib\site-packages\mdpo\md2po\__init__.py", line 624, in markdown_to_pofile
    return Md2Po(
  File "c:\program files\python39\lib\site-packages\mdpo\md2po\__init__.py", line 510, in extract
    _parse(self.content)
  File "c:\program files\python39\lib\site-packages\mdpo\md2po\__init__.py", line 500, in _parse
    parser.parse(
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc93' in position 1705: surrogates not allowed
```

The command that caused the above output: `< $mdfilepath md2po --md-encoding utf-8 --po-encoding utf-8 -e utf-8 -w $width -q -s -c --po-filepath $pofilepath`

The file I ran the command with:
[TSL1401CL_Filament_Width_Sensor.md](https://github.com/mondeja/mdpo/files/6788426/TSL1401CL_Filament_Width_Sensor.md)
