### ISSUE TITLE
Breakage with URLs with IP:port

### ISSUE THREAD

**Issue by ivilata** [mondeja/mdpo#164]
`mdpo` has issues handling some `schema://ip:port/` links. For example, given this `test.md`:

```markdown
A link to <http://127.0.0.1:8080/>.

A link to [http://127.0.0.1:8081/](http://127.0.0.1:8081/).

A link to [localhost][].

[localhost]: http://127.0.0.1:8082/
```

Running `md2po test.md > test.po` yields this (I added the translations manually, except for the fuzzy one):

```po
#
msgid ""
msgstr ""

#: test.md:block 1 (paragraph)
msgid "A link to [http://127.0.0.1:8080/](http://127.0.0.1:8080/)."
msgstr "A0 link to [http://127.0.0.1:8080/](http://127.0.0.1:8080/)."

#: test.md:block 2 (paragraph)
msgid "A link to [http://127.0.0.1:8081/](http://127.0.0.1:8081/)."
msgstr "A1 link to [http://127.0.0.1:8081/](http://127.0.0.1:8081/)."

#: test.md:block 3 (paragraph)
msgid "A link to [localhost][localhost]."
msgstr "A2 link to [localhost][localhost]."

#: test.md:block 3 (paragraph)
#, fuzzy
msgid "[localhost]: http://127.0.0.1:8082/"
msgstr "[localhost]: http://127.0.0.1:8082/"

```

Then running `po2md -p test.po -s /dev/stdout test.md` shows:

```markdown
A link to <http://127.0.0.1:8080/>.

A link to <http://127.0.0.1:8081/>.

A2 link to [localhost][localhost].

[localhost]: http://127.0.0.1:8082/
```

Only the link with textual tag is ok, for the other two it looks like `po2md` was unable to map the `msgstr` to some internal string which should have matched the `msgstr`.

Thanks a lot! :smiley:

**Comment by mondeja** [comment]
First of all, thank you for the report. I've implemented a solution and will be ready in a while with a new [v0.3.68](https://github.com/mondeja/mdpo/releases/tag/v0.3.68) release.

Keep in mind that your example is partially unsupported by CommonMark specification, more specifically in `A link to [localhost][]` due to the [rules of referenced link labels](https://spec.commonmark.org/0.30/#link-label), I quote verbatim:

> A link label begins with a left bracket ([) and ends with the first right bracket (]) that is not backslash-escaped. **Between these brackets there must be at least one character that is not a space, tab, or line ending.**

**Comment by ivilata** [comment]
@mondeja One moment, I read CommonMark link specs more carefully, and a [collapsed reference link](https://spec.commonmark.org/0.30/#collapsed-reference-link) like `[foo][]` and a [shortcut reference link](https://spec.commonmark.org/0.30/#shortcut-reference-link) like `[foo]` should both be valid and equivalent to `[foo][foo]`.

Just saying because I noticed that mdpo 0.3.84 convers my `[foo][]` links in `.md` to `[foo]` links in `.pot`.

**Comment by mondeja** [comment]
Please, could you open another issue to track it showing a clear minimal example? Thanks

**Comment by ivilata** [comment]
> Please, could you open another issue to track it showing a clear minimal example? Thanks

Sure, I just wasn't sure if you considered this relevant enough. Opened #221. Thanks again!
