### ISSUE TITLE
Request: replace url inside MD tag with <link>

### ISSUE THREAD

**Issue by keunes** [mondeja/mdpo#203]
Now that we've [prepared](https://github.com/AntennaPod/antennapod.github.io/pull/112) some important changes to our AntennaPod website structure to get more, easier & better translations, I'm now turning to the translation process itself.

Thanks again @mondeja for helping me install mdpo locally :) I successfully created PO files from a set of MD files and convert them back to translated MDs :)

Now, some of our links are a bit complicated of nature, like these:
`http://llama.location.profiles/AntennaPod+feeds+Update/AntennaPod+feeds+Update%7C0-1-0-0-0-0-0-0-1-0--0-%7C%3A%7Ct%7C420%7C425%7Cai%7Cde.danoeh.antennapod%7CFgAAAGEAbgBkAHIAbwBpAGQALgBjAG8AbgB0AGUAbgB0AC4ASQBuAHQAZQBuAHQAAAAAAP%2F%2F%2F%2F8AAAAA%2F%2F%2F%2F%2FwAAAAD%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FxQAAABkAGUALgBkAGEAbgBvAGUAaAAuAGEAbgB0AGUAbgBuAGEAcABvAGQAAAAAADUAAABkAGUALgBkAGEAbgBvAGUAaAAuAGEAbgB0AGUAbgBuAGEAcABvAGQALgBjAG8AcgBlAC4AcgBlAGMAZQBpAHYAZQByAC4ARgBlAGUAZABVAHAAZABhAHQAZQBSAGUAYwBlAGkAdgBlAHIAAAAAAAAAAAAAAAAAAAAAAAAA%2Fv%2F%2F%2F%2F%2F%2F%2F%2F8%3D%7C2%7C` ([on automation page](https://github.com/keunes/AP-website-copy/blob/main/_i18n/en/documentation/automation/tasker.md?plain=1#L27))
and
`{% if site.lang != 'en' %}/{{ site.lang }}{% endif %}/documentation/general/gpodder` ([on backup page](https://github.com/keunes/AP-website-copy/blob/main/_i18n/en/documentation/general/backup.md?plain=1#L4))

The mdpo [documentation says](https://mdpo.readthedocs.io/en/master/rationale.html#mdpo-approach) that markdown links where the link text and target are the same are automatically replaced by `<link>` in the message.

My request would be that the URLs in markdown link definitions are also replaced with `<link>`. It could then look in the message ID as follows:
```
"gpodder, visit our [documentation section](<link>) about it."
```

This would be easier for translators and has a lower risk of accidental mix-ups by translators.

**Comment by mondeja** [comment]
Sorry, but this would break translations that are using another URL as the target.

For example, given the next Markdown:

```markdown
[Python](https://en.wikipedia.org/wiki/Python_(programming_language)) is my favourite programming language.
```

`md2po` will create this:

```po
#
msgid ""
msgstr ""

msgid ""
"[Python](https://en.wikipedia.org/wiki/Python_(programming_language)) is my "
"favourite programming language."
msgstr ""
```

and I will later translate as:

```po
#
msgid ""
msgstr ""

msgid ""
"[Python](https://en.wikipedia.org/wiki/Python_(programming_language)) is my "
"favourite programming language."
msgstr ""
"[Python](https://es.wikipedia.org/wiki/Python) es mi lenguaje de programación"
" favorito."
```

Note that the URL is changed to use the Spanish wikipedia page, so `po2md` will render:

```markdown
[Python](https://es.wikipedia.org/wiki/Python) es mi lenguaje de programación
favorito.
```

So this is by design.

**Comment by mondeja** [comment]
Oh, I was confused, I understand now 😆 

Are you saying that you've something like this: `[<link>](<link>)`, being both `<link>` the same?

**Comment by mondeja** [comment]
> My request would be that the URLs in markdown link definitions are also replaced with <link>. It could then look in the message ID as follows:

Sorry but no way. If your input are inline links you'll have inline links. If your input are link definitions you'll have link definitions. I don't understand what is the usage case here nor the rationale.

Feel free to reopen it if I've not understood something.
