### ISSUE TITLE
(Option to have) Source content in `msgstr` in PO output file (md2po)

### ISSUE THREAD

**Issue by keunes** [mondeja/mdpo#209]
Hello,

I have set up a GitHub action to create PO files from our MD files using `md2po` and it works as expected: the source content is included as `msgid`. However, when feeding the output PO file to Weblate, because `msgstr` is empty, the 'source text' field is empty:
![afbeelding](https://user-images.githubusercontent.com/11229646/144138397-5345e05f-614d-4c50-be5f-d80ae53e027e.png)

Not having the source text recognised as source text in Weblate has several downsides (e.g. if a string is the same in my language in the source string, I cannot click 'copy' to simply use the source string). A more experienced Weblate user [suggested](https://github.com/WeblateOrg/weblate/discussions/6862#discussioncomment-1712052) that the English text should (also) be used to fill the `msgstr` in the PO file.

Would it be possible & make sense to create an option in `md2po` to use the source text not only as `msgid`, but to also use it to fill `msgstr`?

**Comment by mondeja** [comment]
If Weblate doesn't conforms with [PO files format](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) there is nothing that I can do in mdpo. Quoting the previous linked documentation:

> It is also possible to have entries with a context specifier. They look like this:
> 
> ```
> white-space
> #  translator-comments
> #. extracted-comments
> #: reference…
> #, flag…
> #| msgctxt previous-context
> #| msgid previous-untranslated-string
> msgctxt context
> msgid untranslated-string
> msgstr translated-string
> ```

It is clearly defined that contexts should be defined in `msgctxt`. So I'm closing this, but feel free to reopen it if you don't agree.

**Comment by keunes** [comment]
I'm pretty sure Weblate conforms with the PO file format. However, I think I should have given them a poT file, instead of a PO file. Our site content is showing up properly, now: `msgid` as the Source text, `#: reference` as the Context.

**Comment by mondeja** [comment]
> I think I should have given them a poT file, instead of a PO file.

POT files are just PO files with `msgstr`s empty. Maybe Weblate need the extension `.pot` to recognize them? In that case, you can always specify the `.pot` translation using `md2po`:

```bash
$ printf "Foo" | md2po > foo.pot
$ cat foo.pot
```po
#
msgid ""
msgstr ""

msgid "Foo"
msgstr ""
```
