### ISSUE TITLE
Newlines in table get replaced with space, causing rendering issues

### ISSUE THREAD

**Issue by keunes** [mondeja/mdpo#226]
Hello!

We're using `mdpo` for the translation of the AntennaPod website. Now that we're getting in the first translations, we've noticed that newlines in tables are replaced with spaces when the PO(T) are created, and that this messes up the rendering of the table.

The following table:
```markdown
| Key | Action |
| -- | -- |
|`P` | Play/Pause|
| `J`/`A`/`,` | Rewind media |
| `K`/`D`/`.` | Forward media |
| `+`/`W` | Raise media volume channel |
| `-`/`S` | Lower media volume channel) |
| `M` | Mute/unmute (toggle) media volume channel (only on Android 6 and higher) |
```

when running
```bash
md2po _i18n/en/documentation/*.md --po-filepath _i18n/translation-files/site-documentation.pot --save --quiet
```

turns into
```markdown
#: _i18n/en/documentation/playback/shortcuts.md:block 3 (paragraph)
msgid ""
"| Key | Action | | -- | -- | |`P` | Play/Pause| | `J`/`A`/`,` | Rewind media"
" | | `K`/`D`/`.` | Forward media | | `+`/`W` | Raise media volume channel | "
"| `-`/`S` | Lower media volume channel) | | `M` | Mute/unmute (toggle) media"
" volume channel (only on Android 6 and higher) |"
msgstr ""
```

This, however, creates rendering issues like on this page ([en correct](https://antennapod.org/documentation/playback/shortcuts), [fr not](https://antennapod.org/fr/documentation/playback/shortcuts)).

I realise that tables are [not](https://talk.commonmark.org/t/tables-in-pure-markdown/81/186) ([yet](https://talk.commonmark.org/t/rfc-spec-extension-for-tables-syntax-and-transformation-rules/1910)) part of Commonmark. But given that this actually is just a multiline string, I would expect (based on [this article](https://www.gnu.org/software/gettext/manual/html_node/Normalizing.html)) the PO file to have `\n` instead of a space.

Would this be possible? Or is there an alternative solution that you can think of (e.g. structuring our MD table slightly differently)?

Many thanks!

**Comment by mondeja** [comment]
Your table is not correctly formatted because separators must have 3 characters or more, so the second line must be `| --- | --- |` instead of `| -- | -- |` to be properly parsed. Cheers!
