### ISSUE TITLE
Feature request: md2po argument to exclude lines based on character matching

### ISSUE THREAD

**Issue by joelnitta** [mondeja/mdpo#227]
Instead of [disabling extraction by using comments in the md file](https://mdpo.readthedocs.io/en/master/commands.html#disabling-extraction), I would like to exclude lines by providing a pattern to `md2po` (probably some flavor of grep, but at least literal matching).

Example use case: creating a PO file for an md file with [pandoc fenced divs](https://pandoc.org/MANUAL#extension-fenced_divs), such as [this](https://github.com/carpentries/sandpaper-docs/blob/main/episodes/episodes.Rmd). I would like to be able to exclude all lines starting with three colons (`:::`).

**Comment by mondeja** [comment]
Looks like a legitimate use case. I think that a regex would be the pattern used, but I need to think about that.

The current workaround is to use [events](https://mdpo.readthedocs.io/en/master/cli.html#md2po--e).

Giving the file *foo.md*:

```markdown
:::::::::::::: foo

Foo

::::::::::::::::
```

...and a file `ignorer.py`:

```python
def on_text(md2po, block, text):
    if text.startswith(':::'):
        md2po.disable_next_block = True
```

If you execute `md2po foo.md -e text:ignorer.py::on_text`, you'll get as output:

```po
#
msgid ""
msgstr ""

#: foo.md:block 2 (paragraph)
msgid "Foo"
msgstr ""
```

See [the reference](https://mdpo.readthedocs.io/en/master/devref/mdpo/md2po/mdpo.md2po.__init__.html#mdpo.md2po.__init__.Md2Po) for the exposed API of `md2po` instance passed as first parameter of the event.

**Comment by joelnitta** [comment]
Thanks for the quick reply! At the moment, my workaround for both this and #228 is to pre-process the MD file, then generate the PO file from that. The pre-processing step excludes the YAML header and pandoc fenced divs by automatically adding `<!-- mdpo-disable-next-line -->` etc before the relevant lines.

Eventually, it would be preferable for this to become part `md2po` of so that I don't need an extra file (either ` ignorer.py` or the pre-processed MD).

**Comment by mondeja** [comment]
> Eventually, it would be preferable for this to become part md2po of so that I don't need an extra file (either ignorer.py or the pre-processed MD).

But you will need also a configuration file if this is included, right?

**Comment by mondeja** [comment]
Could you clarify what would be the exact behaviour of this? Would be the pattern a matcher for an entire Markdown block or just part of blocks? I'm not really sure what you're asking for, for example:

```markdown
:::::::::::::: foo
Foo
::::::::::::::::
```

Should this hipotetical new option ignore the `:::` parts of the paragraph? Or only when are defined in separate paragraphs?

```markdown
:::::::::::::: foo

Foo

::::::::::::::::
```

**Comment by joelnitta** [comment]
Sorry if it wasn't sufficiently clear...

I would not try to implement it on the paragraph level, but rather at the level of lines: If a line contains the matched text, it would be excluded from the PO file.

So in that case both
```
:::::::::::::: foo
Foo
::::::::::::::::
```

and

```
:::::::::::::: foo

Foo

::::::::::::::::
```

would only present `Foo` to the PO file.

For your second example, let me explain with pseudo-code. I imagine something like this:

```
md2po input.md --exclude_lines -
```

And it would exclude all of the lines in
```
- foo
- ignore this
- bar
```
because each contains `-`.

**Comment by mondeja** [comment]
MD4C (the parser that uses mdpo based in CommonMark spec) does not parse line by line but block by block, so I can't implement this and I have no motivation to create a low-level line by line Markdown parser that maintains the necessary speed.

There is a PR opened in MD4C to implement the syntax part of the parsing but the author nor have the motivation to end and maintain it. As always, PRs are welcome in MD4C, PyMD4C and mdpo.

**Comment by joelnitta** [comment]
I see, thanks for explaining.

I was under the impression that exclusion / inclusion could be controlled line-by-line because of the existence of both

`<!-- mdpo-disable-next-block -->` or `<!-- mdpo-disable-next-line -->`

and

`<!-- mdpo-enable-next-block -->` or `<!-- mdpo-enable-next-line -->`

Are each of those pairs aliases? In other words, do they all only exclude/enable by block, not by line?

**Comment by mondeja** [comment]
Yes, `<!-- mdpo-disable-next-line -->` is just syntactic sugar for `<!-- mdpo-disable-next-block -->`. See #211

**Comment by patrickbard** [comment]
> MD4C (the parser that uses mdpo based in the CommonMark spec) does not parse line by line but block by block [...]

Does that mean if I had a similar request, for block exclusion, it would be a possibility?

I have some files that I want to include only paragraphs, and ignore all headers.
Is there a better way to do it than adding `<!-- mdpo-disable-next-line -->` before all headers?

**Comment by mondeja** [comment]
> Does that mean if I had a similar request, for block exclusion, it would be a possibility?

Sure, PRs welcome.
