### ISSUE TITLE
YAML header not correctly parsed

### ISSUE THREAD

**Issue by joelnitta** [mondeja/mdpo#228]
Many of the md files I'd like to translate have YAML headers.

For example this `test.md` file:

```
---
some_value: one
---

Regular text here
```

After going from MD -> PO -> MD, the header is not formatted correctly.

```
root@f67677c27f10:/wd# md2po test.md --save test.po -po test.po
#
msgid ""
msgstr ""

#: test.md:block 1 (header)
msgid "some_value: one"
msgstr ""

#: test.md:block 2 (paragraph)
msgid "Regular text here"
msgstr ""
```

```
root@f67677c27f10:/wd# po2md test.md --pofiles test.po
***

## some_value: one

Regular text here

```

OS: Debian 'bullseye' 
```
root@f67677c27f10:/wd# md2po --version
md2po 0.3.85
root@f67677c27f10:/wd# po2md --version
po2md 0.3.85
```

**Comment by mondeja** [comment]
So why you don't use this?

```markdown
<!-- mdpo-disable -->
---
some_value: one
---
<!-- mdpo-enable -->

Regular text here
```

**Comment by joelnitta** [comment]
That still causes the same output:

```
root@f67677c27f10:/wd# cat test.md
<!-- mdpo-disable -->
---
some_value: one
---
<!-- mdpo-enable -->

Regular text here
```

```
root@f67677c27f10:/wd# md2po test.md --save test.po -po test.po
#
#
msgid ""
msgstr ""

#: test.md:block 4 (paragraph)
msgid "Regular text here"
msgstr ""
```

```
root@f67677c27f10:/wd# po2md test.md --pofiles test.po
***

## some_value: one

Regular text here
```

**Comment by mondeja** [comment]
mdpo is based in CommonMark spec. Note that I can't support all the implementations without help. You can always write a text event as I've encouraged you to do in #227

**Comment by mondeja** [comment]
> About what you said, we can see that CommonMark-Spec use the **Front Matter** in its [spec.txt](https://github.com/commonmark/commonmark-spec/blob/9103e341a973013013bb1a80e13567007c5cef6f/spec.txt#L1-L7) as well.
> 
> ```
> ---
> title: CommonMark Spec
> author: John MacFarlane
> version: '0.31.2'
> date: '2024-01-28'
> license: '[CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'
> ...
> ```
> 
> I wonder why the Front Matter is not the standard syntax of CommonMark-Spec?

https://talk.commonmark.org/t/metadata-in-documents/721/73

You can always create an extension, mdpo offers an API for that.

**Comment by mondeja** [comment]
> Hello, @mondeja
> 
> > mdpo is based in CommonMark spec. Note that I can't support all the Markdown implementations without help. You can always write a text event as I've encouraged you to do in #227
> 
> About what you said, we can see that CommonMark-Spec use the **Front Matter** in its [spec.txt](https://github.com/commonmark/commonmark-spec/blob/9103e341a973013013bb1a80e13567007c5cef6f/spec.txt#L1-L7) as well.
> 
> ```
> ---
> title: CommonMark Spec
> author: John MacFarlane
> version: '0.31.2'
> date: '2024-01-28'
> license: '[CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'
> ...
> ```
> 
> I wonder why the Front Matter is not the standard syntax of CommonMark-Spec?

https://talk.commonmark.org/t/metadata-in-documents/721/73

**Comment by mondeja** [comment]
Why not JSON frontmatters, or better JSON5, or YAML-in-fenced-codeblock frontmatters, or whatever language front matters. It's a miracle that a good spec from a technical perspective like that exists.
