### ISSUE TITLE
Preserve HTML in resulted markdown

### ISSUE THREAD

**Issue by binotaliu** [mondeja/mdpo#240]
I have following markdown file:

```markdown
# Title

<div id="my-special-div">
content
</div>

- List Item 1
- List Item 2
```

running `po2md mymd.md --pofile mypo.po --quiet --save result.md` will result following file:

```markdown
# Title

- List Item 1
- List Item 2
```

Is it possible I can reserve the `<div>` in this file?  

I try to read mdpo's source code and was trying to use a `enter_block` hoot to preserve it. This is my hook file:

```python3
import md4c

def skip_entering_html_block(self, block, details):
    if block is md4c.BlockType.HTML:
        return False
```

After running `po2md mymd.md --pofile mypo.po --quiet --save result.md --event enter_block:myhook.py::skip_entering_html_block`, the result markdown file is:

```markdown
# Title

- <div id="my-special-div">
content
</div>
List Item 1

- List Item 2 
```

The `<div>` block becomes the content of the first list item.  

Is it possible to use hook to archive what I want to do?

**Comment by mondeja** [comment]
Fixed in [v1.0.3](https://github.com/mondeja/mdpo/releases/tag/v1.0.3)
