### ISSUE TITLE
[docs] Broken Copyright line

### ISSUE THREAD

**Issue by webknjaz** [mondeja/mdpo#279]
I was browsing RTD and noticed the following at the bottom of the pages:
> ```
> © Copyright 2020-2023, {.
> ```

I suppose it has something to do with what this does: https://github.com/mondeja/mdpo/blob/b60c57d/docs/conf.py#L29-L34. Though I haven't looked any deeper.
FYI.

**Comment by mondeja** [comment]
Thanks!
