### ISSUE TITLE
List item numbering

### ISSUE THREAD

**Issue by bird-in-hat** [mondeja/mdpo#308]
In the current implementation of the Markdown-to-PO translation process, ordered lists (OL) in the Markdown output are incorrectly rendered with each list item starting at 1., regardless of the original numbering in the markdown file.

Problematic Code:
At the following line:
https://github.com/mondeja/mdpo/blob/master/src/mdpo/po2md/__init__.py#L517

The code:

```
python
self.current_line += f'{indent}1{self._ol_marks[-1][1]} '
```
is hardcoding the list item number to 1, which causes each item in the ordered list to incorrectly start with 1. in the output.

Suggested Fix:
To fix this, the numbering should be dynamically assigned based on the tracked count (self._ol_marks[-1][0]). This can be done by modifying the line as follows:

```
python
self.current_line += f'{indent}{self._ol_marks[-1][0]}{self._ol_marks[-1][1]} '
```
This ensures that list item numbering in the Markdown output will properly increment and preserve the correct numeration of the original Markdown's ordered lists.

**Comment by mondeja** [comment]
I think you've noticed that when rendering, HTML numbers them correctly even though they all have the number 1 in the Markdown. See [ordered lists in CommonMark spec](https://spec.commonmark.org/0.31.2/#ordered-list):

> The [start number](https://spec.commonmark.org/0.31.2/#start-number) of an [ordered list](https://spec.commonmark.org/0.31.2/#ordered-list) is determined by the list number of its initial list item. The numbers of subsequent list items are disregarded.
