### ISSUE TITLE
readthedocs seems out of date with master

### ISSUE THREAD

**Issue by gaborbernat** [mondeja/mdpo#63]
https://mdpo.readthedocs.io/en/latest/cli.html#md2po shows still the old sphinx argparse render, even though the master branch contains sphinx-argparse-cli 🤔 You might want to also bump the project, there's been a few improvements lately https://github.com/gaborbernat/sphinx-argparse-cli/blob/main/CHANGELOG.md#150-2021-02-13

Thanks,

**Comment by mondeja** [comment]
Thank you. I've hidden the stable build in ReadTheDocs and, after reloading with CTRL + F5 it seems fixed now :wrench:
