### ISSUE TITLE
Feature request: Metadata headers

### ISSUE THREAD

**Issue by dingyifei** [mondeja/mdpo#85]
A few header entries should be generated for the PO file [gettext headers](https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html) (maybe a parameter that could be passed multiple times with header pairs?) I encountered some errors in Weblate when I tried to use the `Update PO files to match POT (msgmerge)` add-on, where it threw an error about missing encoding at the start of the PO files.

A header would look like this
```
#
msgid ""
msgstr ""
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
```

BTW, there is a bounty on markdown file support for Weblate. The total is $250 +1 XMR I believe. 

Link to that issue https://github.com/WeblateOrg/weblate/issues/3106

**Comment by mondeja** [comment]
I've had this in mind for a long time, but just never needed it. Not only the "Content-Type" and "Content-Transfer-Encoding" headers, but other common PO metadata headers like "Language", "Language-Team", "Last-Translator"... definitively it seems that it is worth adding parameters for the most common and another parameter to define additional ones :+1:

**Comment by mondeja** [comment]
| Header name | CLI parameter | Argument Name |
| --- | --- | --- |
| Project-Id-Version | --project-id-version | project_id_version |
| Report-Msgid-Bugs-To | --report-msgid-bugs-to | report_msgid_bugs_to |
| PO-Revision-Date | --po-revision-date | po_revision_date |
| Last-Translator | --last-translator | last_translator |
| Language-Team | --language-tem | language_team |
| Language | --language | language |
| Content-Type | --content-type | content_type |
| Content-Transfer-Encoding | --content-transfer-encoding | content_transfer_encoding |
| Plural-Forms | --plural-forms | plural_forms |
| MIME-Version | --mime-version | mime_version |
| *                    | --metadata "Key: Value" | metadata={} |

**Comment by mondeja** [comment]
This has been added in [v0.3.30](https://github.com/mondeja/mdpo/releases/tag/v0.3.30). You can use `--metadata "Key: Value"` or just `-d "Key: Value"`. In the end I have decided not to add different arguments for each field, this `--metadata` argument should be enough.
